# This is a basic workflow to help you get started with Actions

name: NseMQ-Ubuntu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # use librdkafka
    #- uses: edenhill/librdkafka/master
    
    # create nsemq-all root directory
    - name: create nsemq-all root directory
      run : |
        cd /usr/local/
        sudo mkdir nsemq-all
        cd nsemq-all
        echo "*** create include and lib directory"
        sudo mkdir include lib
        cd include
        sudo mkdir librdkafka avro boost         
    
    # install avro dependencies
    - name: install avro dependencies
      run: |
       sudo apt-get -y --force-yes install libboost-dev
       sudo apt-get -y --force-yes install libboost-filesystem-dev
       sudo apt-get -y --force-yes install libboost-iostreams-dev
       sudo apt-get -y --force-yes install libboost-program-options-dev
       sudo apt-get -y --force-yes install libboost-system-dev
       apt-cache search libboost-dev
        
    # install avro
    - name: install avro
      run: |
        cd /usr/local/nsemq-all/
        sudo mkdir avro-all
        cd avro-all
        sudo wget https://downloads.apache.org/avro/avro-1.9.2/cpp/avro-cpp-1.9.2.tar.gz
        echo "*** untar wget files"
        sudo tar -xzf avro-cpp-1.9.2.tar.gz
        cd avro-cpp-1.9.2
        echo "*** view avro files"
        ls
        sudo ./build.sh test
        sudo ./build.sh install
        echo "*** view avro install files"
        ls
        
        
        
    
    # install librdkafka
    # - name: install librdkafka
    #  run: apt install librdkafka-dev

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Hello, world!
        echo Add other actions to build,
        echo test, and deploy your project.
        
    
