# This is a basic workflow to help you get started with Actions

name: ubuntuCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # use librdkafka
    #- uses: edenhill/librdkafka/master
    
    # create nsemq-all root directory
    - name: create nsemq-all root directory
      run : |
        cd /usr/local/
        sudo mkdir nsemq-all
        cd nsemq-all
    
    # git and install librdkakfa
    - name: git and install librdkakfa
      run: |
        sudo mkdir librdkafka-all
        cd librdkafka-all
        sudo git clone https://github.com/edenhill/librdkafka.git
        echo "****view git files"
        cd librdkafka
        sudo ./configure --install-deps
        sudo make
        sudo make install
        # view directory
        sudo find . -name 'librdkafka.so.1'
        cd /usr/local/lib
        echo "view lib"
        ls

        
    
    # install librdkafka
    # - name: install librdkafka
    #  run: apt install librdkafka-dev

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Hello, world!
        echo Add other actions to build,
        echo test, and deploy your project.
